name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v4
      - name: Use Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          name: Tests
          on: 
  push:
    branches:
    - 'main'
    jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 'current'
          run: npm ci
      - name: Build Packages
        run: npm run build
      - name: Run Unit Tests
        run: npm run tests
      - name: Run Integration Tests
          'test integration'
          'Check lint'
             'Run lint
            [ 'Build' ]
